import Footer from '@/component/footer'
import LookBox from '@/component/lookBox'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/assets/css/main.min.css"></link>
        <script
            defer
            src="/assets/js/neuro.js"
          />
      </head>
      <body style={{
        'position': 'relative',
        'background': '#006BB3',
        'backgroundColor': '#006BB3'
        }}>
          <canvas id="canvas"></canvas>
          <main className='main'>
            {children}
          </main>
          <LookBox />
          <Footer />
      </body>
    </html>
  )
}
